### ISSUE TITLE
Missing android.support.media.ExifInterface dependency

### ISSUE THREAD

**Issue by enghoff** [thedoritos/unimgpicker#15]
Thanks for a well-developed plugin. Regrettably I am getting a dependency issue on Android with class android.support.media.ExifInterface missing. Do you have any suggestion for how this may be resolved?

Stack trace as follows -

Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/media/ExifInterface;
	at com.kakeragames.unimgpicker.Picker.onActivityResult(Picker.java:122)
	at android.app.Activity.dispatchActivityResult(Activity.java:6982)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4049)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4096)
	at android.app.ActivityThread.-wrap20(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.media.ExifInterface" on path: DexPathList[[zip file "/data/app/com.longworld.facedoku-1/base.apk"],nativeLibraryDirectories=[/data/app/com.longworld.facedoku-1/lib/arm, /data/app/com.longworld.facedoku-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at com.kakeragames.unimgpicker.Picker.onActivityResult(Picker.java:122) 
	at android.app.Activity.dispatchActivityResult(Activity.java:6982) 
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4049) 
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4096) 
	at android.app.ActivityThread.-wrap20(ActivityThread.java) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516) 
	at android.os.Handler.dispatchMessage(Handler.java:102) 
	at android.os.Looper.loop(Looper.java:154) 
	at android.app.ActivityThread.main(ActivityThread.java:6077) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by enghoff** [comment]
Although the issue persists when building the component using Unity's "internal" (ANT) build system the dependency issue is not present when building through Gradle

**Comment by thedoritos** [comment]
Hi, @enghoff . Thank you for reporting the issue.

I assume you are using the code at `fix/image_rotation` branch.
The code in the branch uses `ExifInterface` to get the orientation of the image saved in the phone.

[ExifInterface | Android Developers](https://developer.android.com/reference/android/support/media/ExifInterface.html)

Though Unimgpicker uses Gradle to get the implementation, I think you can include it manually in JAR (or AAR) format.

You can download JARs using SDK Manager. And copy required JARs into your project.

If you are not sure where to place the JAR, following Q&A may help.

[Where can .jar files be placed under Assets/Plugins/Android? - Unity Answers](https://answers.unity.com/questions/837762/where-can-jar-files-be-placed-under-assetspluginsa.html)

--

I'm sorry I don't have time to test this approach by self now.

**Comment by enghoff** [comment]
You are right, I am on the `fix/image_rotation` branch 😄 

I agree that manually including the JAR/AAR would likely do the trick, but I have not been able to locate an Android support archive that contains the `ExifInterface` class. It is less immediately critical now that I got the project compiling with Gradle, but if you are able to point me to a JAR/AAR, I'd be happy to validate that it builds and works with your code.
