### ISSUE TITLE
Unity 5.5.0f3 / Device: Samsung Galaxy S7 (Android: 6.0.1)

### ISSUE THREAD

**Issue by ghost** [thedoritos/unimgpicker#2]
After selecting image in library  I got crash with this stack
Build from MacOS Sierra (10.12.3)
```
//Picker.java line 116
Caused by java.lang.IllegalArgumentException: width and height must be > 0
       at android.graphics.Bitmap.createBitmap(Bitmap.java:967)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:877)
       at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:753)
       at com.kakeragames.unimgpicker.Picker.onActivityResult(Picker.java:116)
       at android.app.Activity.dispatchActivityResult(Activity.java:7161)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4921)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4142)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4250)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3361)
       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by thedoritos** [comment]
Thanks for reporting the issue. I'll investigate it on next weekend.

**Comment by thedoritos** [comment]
Hi, @groznybear 

Could you give me more information? I added an activity to help debugging :bug:

1. Checkout the branch `fix/crash_on_galaxy_s7`.
1. Open the Android project at `unimgpicker_android` with Android Studio.
1. Run `app` with debug mode on your device.
1. Set some breakpoints and find out what's going wrong within `Picker.java` lines 93-123.

It seems the value of `opts.outWidth` at the line 106 to be zero.
That is probably because reading image options at lines 96-98 is somehow failing.

```java
// Decode metadata
BitmapFactory.Options opts = new BitmapFactory.Options();
opts.inJustDecodeBounds = true;
BitmapFactory.decodeStream(inputStream, null, opts);
inputStream.close();
```

Thank you.

- - -

FYI, I run the sample scene on following environment, and it worked.

Device: Nexus 5
OS: Android 6.0.1
Unity: 5.5.1f1

**Comment by ghost** [comment]
Hi, after couple of weeks of "bug fixing", seems like I found the reason of my problem! Seems like I accidentally turned on "Do not keep activities" switch, under "Developers" tab in Settings. Turning it off fixed the problem. I'm sorry I disturbed you! You may check this option, if that was an actual reason. Thank you for your attention! Plugin works well now!

**Comment by thedoritos** [comment]
Thanks for the report. I'm happy to hear the plugin is working.
Feel free to report another issue if you find any bugs or inconveniences.

Thank you :)
