### ISSUE TITLE
Unity 2018.3.0b5 Android Gradle Build Failed

### ISSUE THREAD

**Issue by kaninhot004** [thedoritos/unimgpicker#25]
I was face the problem with Gradle Build but Internal (Deprecated) is okay.
```CommandInvokationFailure: Gradle build failed. 
C:/Program Files/Java/jdk1.8.0_181\bin\java.exe -classpath "C:\Program Files\Unity 2018.3.0b5\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-4.6.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx40966m" "assembleRelease"

stderr[
D8: Program type already present: com.kakeragames.unimgpicker.BuildConfig
java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: D:\Workspace\ferretking\emembercardappadmin\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\45, D:\Workspace\ferretking\emembercardappadmin\Temp\gradleOut\build\intermediates\transforms\externalLibsDexMerger\release\0, D:\Workspace\ferretking\emembercardappadmin\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\41.jar, D:\Workspace\ferretking\emembercardappadmin\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\43.jar
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Program type already present: com.kakeragames.unimgpicker.BuildConfig
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:406)
	at com.android.build.gradle.internal.transforms.DexMergerTransform.transform(DexMergerTransform.java:228)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:221)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:217)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:212)
	at sun.reflect.GeneratedMethodAccessor394.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: D:\Workspace\ferretking\emembercardappadmin\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\45, D:\Workspace\ferretking\emembercardappadmin\Temp\gradleOut\build\intermediates\transforms\externalLibsDexMerger\release\0, D:\Workspace\ferretking\emembercardappadmin\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\41.jar, D:\Workspace\ferretking\emembercardappadmin\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\43.jar
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Program type already present: com.kakeragames.unimgpicker.BuildConfig
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1431)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: D:\Workspace\ferretking\emembercardappadmin\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\45, D:\Workspace\ferretking\emembercardappadmin\Temp\gradleOut\build\intermediates\transforms\externalLibsDexMerger\release\0, D:\Workspace\ferretking\emembercardappadmin\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\41.jar, D:\Workspace\ferretking\emembercardappadmin\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\43.jar
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Program type already present: com.kakeragames.unimgpicker.BuildConfig
	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:129)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:114)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:101)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:36)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	... 4 more
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:71)
	at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:41)
	at com.android.tools.r8.D8.run(D8.java:89)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:112)
	... 7 more
Caused by: com.android.tools.r8.utils.AbortException: Error: Program type already present: com.kakeragames.unimgpicker.BuildConfig
	at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:83)
	at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:62)
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:62)
	... 10 more


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformDexArchiveWithDexMergerForRelease'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: D:\Workspace\ferretking\emembercardappadmin\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\45, D:\Workspace\ferretking\emembercardappadmin\Temp\gradleOut\build\intermediates\transforms\externalLibsDexMerger\release\0, D:\Workspace\ferretking\emembercardappadmin\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\41.jar, D:\Workspace\ferretking\emembercardappadmin\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\43.jar
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: com.kakeragames.unimgpicker.BuildConfig

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
]
stdout[
:preBuild UP-TO-DATE
:OneSignalConfig:preBuild UP-TO-DATE
:OneSignalConfig:preReleaseBuild UP-TO-DATE
:OneSignalConfig:checkReleaseManifest
:OneSignalConfig:processReleaseManifest
:Unimgpicker:preBuild UP-TO-DATE
:Unimgpicker:preReleaseBuild UP-TO-DATE
:Unimgpicker:checkReleaseManifest
:Unimgpicker:processReleaseManifest
:preReleaseBuild
:OneSignalConfig:compileReleaseAidl NO-SOURCE
:Unimgpicker:compileReleaseAidl NO-SOURCE
:compileReleaseAidl NO-SOURCE
:OneSignalConfig:packageReleaseRenderscript NO-SOURCE
:Unimgpicker:packageReleaseRenderscript NO-SOURCE
:compileReleaseRenderscript UP-TO-DATE
:checkReleaseManifest UP-TO-DATE
:generateReleaseBuildConfig UP-TO-DATE
:prepareLintJar UP-TO-DATE
:mainApkListPersistenceRelease UP-TO-DATE
:generateReleaseResValues UP-TO-DATE
:generateReleaseResources UP-TO-DATE
:OneSignalConfig:compileReleaseRenderscript
:OneSignalConfig:generateReleaseResValues
:OneSignalConfig:generateReleaseResources
:OneSignalConfig:packageReleaseResources
:Unimgpicker:compileReleaseRenderscript
:Unimgpicker:generateReleaseResValues
:Unimgpicker:generateReleaseResources
:Unimgpicker:packageReleaseResources
:mergeReleaseResources UP-TO-DATE
:createReleaseCompatibleScreenManifests UP-TO-DATE
:processReleaseManifest
:splitsDiscoveryTaskRelease UP-TO-DATE
:OneSignalConfig:platformAttrExtractor
:Unimgpicker:platformAttrExtractor
:OneSignalConfig:generateReleaseBuildConfig
:OneSignalConfig:prepareLintJar UP-TO-DATE
:OneSignalConfig:javaPreCompileRelease
:OneSignalConfig:processReleaseJavaRes NO-SOURCE
:Unimgpicker:generateReleaseBuildConfig
:Unimgpicker:prepareLintJar UP-TO-DATE
:Unimgpicker:javaPreCompileRelease
:Unimgpicker:processReleaseJavaRes NO-SOURCE
:compileReleaseNdk NO-SOURCE
:mergeReleaseShaders UP-TO-DATE
:compileReleaseShaders UP-TO-DATE
:generateReleaseAssets UP-TO-DATE
:OneSignalConfig:mergeReleaseShaders
:OneSignalConfig:compileReleaseShaders
:OneSignalConfig:generateReleaseAssets
:OneSignalConfig:packageReleaseAssets
:Unimgpicker:mergeReleaseShaders
:Unimgpicker:generateReleaseRFile
:Unimgpicker:generateReleaseSources
:Unimgpicker:compileReleaseJavaWithJavac
:Unimgpicker:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
:Unimgpicker:compileReleaseShaders
:Unimgpicker:generateReleaseAssets
:Unimgpicker:packageReleaseAssets
:mergeReleaseAssets
:mergeReleaseJniLibFolders UP-TO-DATE
:OneSignalConfig:compileReleaseNdk NO-SOURCE
:OneSignalConfig:mergeReleaseJniLibFolders
:OneSignalConfig:generateReleaseRFile
:processReleaseResources
:generateReleaseSources
:OneSignalConfig:generateReleaseSources
:OneSignalConfig:compileReleaseJavaWithJavac
:OneSignalConfig:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
:javaPreCompileRelease UP-TO-DATE
:compileReleaseJavaWithJavac
:compileReleaseSources
:lintVitalRelease
:transformClassesWithDexBuilderForRelease
C:\Users\TARTs\.gradle\caches\transforms-1\files-1.1\com.google.firebase.firebase-messaging-12.0.1.aar\fe6b18962577d4fff28fca13a5e49969\jars\classes.jar: D8: Type `com.google.android.gms.measurement.AppMeasurement` was not found, it is required for default or static interface methods desugaring of `com.google.android.gms.measurement.AppMeasurement com.google.firebase.messaging.zzc.zzde(android.content.Context)`
C:\Users\TARTs\.gradle\caches\transforms-1\files-1.1\com.google.firebase.firebase-messaging-12.0.1.aar\fe6b18962577d4fff28fca13a5e49969\jars\classes.jar: D8: Type `com.google.android.gms.measurement.AppMeasurement` was not found, it is required for default or static interface methods desugaring of `com.google.android.gms.measurement.AppMeasurement com.google.firebase.messaging.zzd.zzde(android.content.Context)`
:transformDexArchiveWithExternalLibsDexMergerForRelease
:transformDexArchiveWithDexMergerForRelease FAILED
53 actionable tasks: 38 executed, 15 up-to-date
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <480e50343593457c94864bd38c09a2ca>:0)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <480e50343593457c94864bd38c09a2ca>:0)
UnityEdit<message truncated>```

**Comment by nitishmehta3** [comment]
I am also facing the Android gradle build fail issue. Is there anything specific that needs to be done for gradle build. I got below error:

Build Failed:
com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lcom/kakeragames/unimgpicker/BuildConfig; See the Console for details.

**Comment by kaninhot004** [comment]
Unity 2018.3.0b8 (64-bit)
play-services-resolver_v1.2.95.0

I don't know this help or not you can try.

Assets\Plugins\Android\Unimgpicker\AndroidManifest.xml

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.kakeragames.unimgpicker">
  <application>
  </application>
</manifest>`

Try build with internal first if can't then gradle

Reset default for everything in player setting
Check preference in Unity to use embed jdk
Use lastest ndk
Use lastest sdk

**Comment by shraddha360** [comment]
Same issue i am also facing

**Comment by ramkeshcse084** [comment]
I got this useful for me. https://www.youtube.com/watch?v=ME0v_1B0sGw

**Comment by thedoritos** [comment]
Hi! This was because `unimgpicker.jar` was containing `BuildConfig.class`. Since Unimgpicker doesn't have to use BuildConfig, I removed it from jar on v1.1.2. It should pass build.

https://github.com/thedoritos/unimgpicker/releases/tag/v1.1.2
